<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPWX4ozk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPWX4ozk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPWX4ozk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPWX4ozk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPWX4ozk\App_KernelDevDebugContainer([
    'container.build_hash' => 'PWX4ozk',
    'container.build_id' => '57171039',
    'container.build_time' => 1727095638,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPWX4ozk');
