<?php

namespace ContainerPWX4ozk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemoControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DDmiP8z.App\Controller\DemoController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DDmiP8z.App\\Controller\\DemoController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'slugify' => ['privates', 'App\\Service\\Slugify', 'getSlugifyService', true],
        ], [
            'slugify' => 'App\\Service\\Slugify',
        ]))->withContext('App\\Controller\\DemoController::index()', $container);
    }
}
